--- #YAML:1.0
name:                Email-Send-IO
version:             2.200
abstract:            Send mail via IO::All
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
    Email::Send:                   2.186
    IO::All:                       0.32
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Casey West <casey@geeknest.com>
